import type { Metadata } from "next";
import { Enriqueta } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/dashboard/navbar";

const enriqueta = Enriqueta({
  weight: "400",
  variable: "--font-serif-text",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FloatChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={enriqueta.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
